### ISSUE TITLE
What is your favorite brand of queso?

### ISSUE THREAD

**Issue by cryptoquick** [queso/ama#1]
And if you don't have a particular brand you prefer, do you make your own, and if so, how do you or your wife prepare it? :smile_cat:

**Comment by queso** [comment]
I generally don't eat queso, oddly enough. The nickname came out of playing on a Diku MUD called SlothMUD many years ago. I just chose many different food based names for characters such as Queso, Chile, Guacamole, Carne, etc. Queso was the one that got the magic reroll token and I hit great stats, so it became my main character.

I later started a lanparty with some of my friends from the MUD and the name just stuck with me.

I guess I like ordering queso when we go to a mexican restaurant, but no idea on a brand :)
