### ISSUE TITLE
What are the best & worst parts of being a community leader?

### ISSUE THREAD

**Issue by StanLindsey** [queso/ama#5]
You're a big voice in the Meteor community, whats great about that but also what frustrates you?

**Comment by queso** [comment]
I guess I've never really considered myself a community leader, so I am not sure I've thought about this much...

I tend to just speak my mind about things that I am working on or encountering in my daily work. Most of my blog post ideas come from things I've worked on for a client recently, most of them agree to let me post about that work in an anonymized way.

I guess my podcasting (Meteor Podcast and now Crater Podcast) around Meteor news might propel me more into a large community voice, but again, I am mostly just responding with my own opinions. In that regard, I guess way back in the day it was frustrating that MDG was so silent for a long time, but @benstr has been doing his best to make that better. 

That being said, I realize that my work and what I can offer the world at large might be better served if I expand outside of just Meteor, so I've been focused on javascript ecosystem as a whole this year.
