### ISSUE TITLE
Meteor App dev in Windows

### ISSUE THREAD

**Issue by JamesReece** [queso/ama#6]
Hi Josh,

New to web dev, I played with RoR, PHP, ASP (I'm c# guy) and when I stumbled upon Meteor, I loved it.  Have not looked back and feel invested in it.  Followed many tuts, built (not finished) a few web pages and want to get started on the stack of apps I want to build.  The simplest lends itself to mobile more than web, so I found myself looking at AngularMeteor with ionic libs (a la the whatsapp example if you know it).  But I am on a windows laptop... I cannot use platform-add for viewing emulator.  And of course, no xcode.  I've tried virtual linux meteor containers but didn't get very far.

Would you say to someone starting out that windows is just not quite right for app dev?  Am I missing something (I don't see the Chrome small device view as a proper solution)?  In the meantime I've returned to building a web landing page for routing links to if the app is not installed on device but I am kicking the can down the road...

**Comment by queso** [comment]
I personally haven't use Windows for 10+ years and I don't miss it at all, so I may be biased in my answer. I think having a mac certainly makes it much easier to match up with the majority of devs out there who are building things for the web. Of course, I know plenty of people are using Linux to do dev work too. XCode will be the one thing you will miss out on without having a mac. Worth getting one imo.
